name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm i
    
    - name: Build website
      run: npm run build
      env:
        CI: false
    
    - name: Copy to machine
      uses: appleboy/scp-action@master
      with:
        host: "ruins.hydrocode.de"
        username: root
        key: ${{ secrets.SCP_KEY }}
        source: build/*
        target: /var/www/html
        strip_components: 1